region          = "eu-central-1"
subnet_region   = "eu-central-1a"
vpc_name        = "main-vpc"
instance_type   = "t2.micro"
instance_ami    = "ami-0caef02b518350c8b"
key_pair_name   = "ssh-from-home"
